default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: anton
  password: 

development:
  <<: *default
  database: zooclan_development

test:
  <<: *default
  database: zooclan_test

production:
  <<: *default
  database: zooclan_production
